services:
  build_keeper:
    build: .
    image: app-aesiron-build_keeper
    container_name: app-aesiron-build_keeper
    volumes:
      - ${APP_HOST_PATH:-.}/app:/app
    ports:
      - "8503:8503"
    env_file:
      - .env
    networks:
      - aesiron-net

networks:
  aesiron-net:
    external: true
